version: "3.7"

services:
  postgres:
    container_name: email-service-postgres
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - email-service-postgres-data:/data/postgres
      - ./sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
    networks:
      - postgres
    env_file:
      - env/EmailServicePostgres.env
    
  
networks:
  postgres:
    driver: bridge

volumes:
  email-service-postgres-data:
    name: email-service-postgres-data
