import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import PostCardsComponent from '../web/components/post-cards/post-cards.component'
import NavbarComponent from '../web/components/navbar/navbar.component'
import LoginComponent from '../web/components/login/login.component'
import { useEffect, useState } from "react";
import { createUser, getUser } from '../web/requests'
import { useSession } from "next-auth/react";
import { GlobalState } from '../web/mobx/globalState'
import { observer } from 'mobx-react-lite'

const inter = Inter({ subsets: ['latin'] })
const globalState = new GlobalState()

const Home = observer(() => {

  const { data: session } = useSession();

  const searchUser = async () => {
    const user = await getUser(session?.user?.email!)
    
    if(user === null) {
      createUser(session?.user?.name!, session?.user?.email!)
          .then(() => console.log('Se creeaza utilizatorul!'))
          .catch((e: any) => console.log(e))
          .finally(() => console.log('Utilizatorul a fost creat!'))
    }
  }

  useEffect(
    () => {

        if(session === undefined) return;
        searchUser();
    },
    [session]
) 


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <PostCardsComponent/>
      </main>
    </>
  )
})

export default Home;
